version: "3.7"

services:
  postgres:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_DB=covid
      - POSTGRES_USER=covid
      - POSTGRES_PASSWORD=goaway
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: "api"
    ports:
      # This is externalPort:internalPort, for the record
      - "8080:8080"
