defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build-ui:
    <<: *defaults
    docker:
      node: circleci/node@1.1.6
    steps:
      - checkout
      - run:
          name: Move to code
          command: |
            cd ui
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - build
  build-api:
    <<: *defaults
    docker:
      - image: circleci/golang:1.12
    steps:
      - run:
          name: Build
          command: go build .
      - persist_to_workspace:
          root: ./
          paths:
            - demand-modeling
workflows:
  version: 2
  test-deploy:
    jobs:
      - build-ui
      - build-api
