defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build-ui:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "ui/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd ui && yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "ui/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Test
          command: |
            cd ui && yarn run test
      - run:
          name: Build
          command: cd ui && yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - ui/build
  build-api:
    <<: *defaults
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Test
          command: go test -race ./...
      - persist_to_workspace:
          root: ./
          paths:
            - demand-modeling
            - manifest.yml
  deploy-cloudgov:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install cloud.gov dependencies
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
      - run:
          name: Login to cloud.gov
          command: cf login -a https://api.fr.cloud.gov -u $CF_USER -p $CF_PASS -o $CF_ORG -s $CF_SPACE
      - run:
          name: Deploy to cloud.gov
          command: npm run deploy
workflows:
  version: 2
  deploy:
    jobs:
      - build-ui
      - build-api
  deploy-cloudgov:
    jobs:
      - deploy-cloudgov:
          filters:
            branches:
              only: ronheft/ci-autodeploy
